export enum MensajesExitosos {
    ALUMNO_MODIFICADO = 'El alumno ha sido modificado correctamente',
    ALUMNO_CREADO = 'El alumno ha sido creado correctamente',
    ALTA_OFERTA = 'La oferta educativa ha sido agregada correctamente',
    INUTILIZADO_NROSERIE = 'El Número de serie fue inutilizado correctamente',
    TITULO_CREADO = 'El título se cargó correctamente',
    TITULO_MODIFICADO = 'El título se modificó correctamente',
    METODO_CALIFICACION_CREADO = 'El método de calificación ha sido creado correctamente',
    METODO_CALIFICACION_MODIFICADO = 'El método de calificación ha sido modificado correctamente',
    ALTA_PLAN_EDUCATIVO = 'El plan educativo ha sido creado correctamente',
    ALTA_MATERIA_DENOMINACION = 'La materia denominación ha sido creada correctamente',
    MODIF_MATERIA_DENOMINACION = 'La materia denominación ha sido modificada correctamente',
    MODIF_PLAN_EDUCATIVO = 'El plan educativo ha sido modificado correctamente',
    MODIF_CURSO_GRUPO_NOMBRE = 'El nuevo nombre de cursos se ha guardado correctamente',
    ALTA_CURSO_GRUPO_NOMBRE = 'El nuevo nombre de cursos se ha guardado correctamente',
    MODIF_CURSO_GRUPO = 'El curso se modificó correctamente',
    ALTA_CURSO_GRUPO = 'El curso se agregó correctamente',
    NUEVA_EDAD = 'La edad fue dada de alta correctamente',
    NUEVA_CORRESPONDENCIA = 'La correspondencia fue dada de alta correctamente',
    NUEVA_LEY_DE_EDUCACION = 'La nueva ley fue dada de alta correctamente',
    NUEVA_NORMA_APROBACION = 'La nueva norma de aprobación fue dada de alta correctamente',
    NUEVA_NORMA_DICTAMEN = 'La nueva norma dictamen fue dada de alta correctamente',
    DUPLICADA_OFERTA = 'La oferta educativa ha sido duplicada correctamente',
    PEGADA_OFERTA = 'La oferta educativa ha sido pegada correctamente',
    BAJA_OFERTA = 'La oferta educativa fue dada de baja correctamente',
    HABILITADA_OFERTA = 'La oferta educativa fue habilitada correctamente'
}
